version: '3.8'
services:
  db:
    image: postgres:15
    container_name: effective_mobile_db
    environment:
      POSTGRES_DB: effective_mobile
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data